// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrustRegistryService.Infrastructure.Data;

#nullable disable

namespace TrustRegistryService.Infrastructure.Migrations
{
    [DbContext(typeof(TRDbContext))]
    [Migration("20250930004245_ResolveStatusEntity")]
    partial class ResolveStatusEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TrustRegistryService.Core.Entity.TrustRegistry", b =>
                {
                    b.Property<string>("IssuerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IssuerId");

                    b.HasIndex("IssuerId")
                        .IsUnique();

                    b.ToTable("TrustRegistries");
                });
#pragma warning restore 612, 618
        }
    }
}
