// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrustRegistryService.Infrastructure.Data;

#nullable disable

namespace TrustRegistryService.Infrastructure.Migrations
{
    [DbContext(typeof(TRDbContext))]
    [Migration("20260119025904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrustRegistryService.Core.Entity.TrustRegistry", b =>
                {
                    b.Property<string>("IssuerId")
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IssuerId");

                    b.HasIndex("IssuerId")
                        .IsUnique();

                    b.ToTable("TrustRegistries");
                });
#pragma warning restore 612, 618
        }
    }
}
